name: 'teste docker'
description: 'teste docker'
inputs:
  docker-run-options:
    description: "Paramentros para o docker Run"
    default: ""
    required: false

# outputs:
#   time: # id of output
#     description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - "qualquercoisa"
    - "qualquercoisa2"

  # using: "composite"
  # steps:
  # - name: "Build Image docker"
  #   run: |
  #     cd $GITHUB_ACTION_PATH
  #     docker build -t docker-action:latest  . 
  #   shell: bash
  
  # - name: "Run Image docker"
  #   run: |
  #     docker run ${{ inputs.docker-run-options }} docker-action:latest
  #   shell: bash