name: 'teste docker'
description: 'teste docker'
inputs:
  docker-options:
    description: "Faz o de detach do run do container"
    default: ""
    required: false

# outputs:
#   time: # id of output
#     description: 'The time we greeted you'
runs:
  # using: 'docker'
  # image: 'Dockerfile'
  using: "composite"
  steps:
  - name: "Build Image docker"
    run: |
      cd $GITHUB_ACTION_PATH
      docker build -t docker-action:latest  . 
    shell: bash
  
  - name: "Run Image docker"
    run: |
      docker run ${{ inputs.docker-options }} docker-action:latest
    shell: bash