name: 'teste docker'
description: 'teste docker'
inputs:
  docker-run-options:
    description: "Paramentros para o docker Run"
    default: ""
    required: false

# outputs:
#   time: # id of output
#     description: 'The time we greeted you'
runs:
  # using: 'docker'
  # image: 'Dockerfile'
  # args:
  #   - "qualquercoisa"
  #   - "qualquercoisa2"

  #/usr/bin/docker run --name b8291d8a1a7a14551b0af9a6ea4fdcda1_d25cbf --label 94351b --workdir /github/workspace --rm -e "INPUT_DOCKER-RUN-OPTIONS" -e "HOME" -e "GITHUB_JOB" -e "GITHUB_REF" -e "GITHUB_SHA" -e "GITHUB_REPOSITORY" -e "GITHUB_REPOSITORY_OWNER" -e "GITHUB_REPOSITORY_OWNER_ID" -e "GITHUB_RUN_ID" -e "GITHUB_RUN_NUMBER" -e "GITHUB_RETENTION_DAYS" -e "GITHUB_RUN_ATTEMPT" -e "GITHUB_REPOSITORY_ID" -e "GITHUB_ACTOR_ID" -e "GITHUB_ACTOR" -e "GITHUB_TRIGGERING_ACTOR" -e "GITHUB_WORKFLOW" -e "GITHUB_HEAD_REF" -e "GITHUB_BASE_REF" -e "GITHUB_EVENT_NAME" -e "GITHUB_SERVER_URL" -e "GITHUB_API_URL" -e "GITHUB_GRAPHQL_URL" -e "GITHUB_REF_NAME" -e "GITHUB_REF_PROTECTED" -e "GITHUB_REF_TYPE" -e "GITHUB_WORKFLOW_REF" -e "GITHUB_WORKFLOW_SHA" -e "GITHUB_WORKSPACE" -e "GITHUB_ACTION" -e "GITHUB_EVENT_PATH" -e "GITHUB_ACTION_REPOSITORY" -e "GITHUB_ACTION_REF" -e "GITHUB_PATH" -e "GITHUB_ENV" -e "GITHUB_STEP_SUMMARY" -e "GITHUB_STATE" -e "GITHUB_OUTPUT" -e "RUNNER_OS" -e "RUNNER_ARCH" -e "RUNNER_NAME" -e "RUNNER_ENVIRONMENT" -e "RUNNER_TOOL_CACHE" -e "RUNNER_TEMP" -e "RUNNER_WORKSPACE" -e "ACTIONS_RUNTIME_URL" -e "ACTIONS_RUNTIME_TOKEN" -e "ACTIONS_CACHE_URL" -e "ACTIONS_ID_TOKEN_REQUEST_URL" -e "ACTIONS_ID_TOKEN_REQUEST_TOKEN" -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/actions-lab/actions-lab":"/github/workspace" 94351b:8291d8a1a7a14551b0af9a6ea4fdcda1  "qualquercoisa" "qualquercoisa2"

  using: "composite"
  steps:
  - name: "Build Image docker"
    run: |
      cd $GITHUB_ACTION_PATH
      docker build -t docker-action:latest "qualquer coisa" "qualquercoisa2" . 
    shell: bash
  
  # - name: "Run Image docker"
  #   run: |
  #     docker run ${{ inputs.docker-run-options }} docker-action:latest
  #   shell: bash