name: 'teste docker'
description: 'teste docker'

# outputs:
#   time: # id of output
#     description: 'The time we greeted you'
runs:
  # using: 'docker'
  # image: 'Dockerfile'
  using: "composite"
  steps:
  - name: "Build Image docker"
    run: |
      ls -lia $GITHUB_ACTION_PATH
      cat "$GITHUB_ACTION_PATH/Dockerfile"
      docker --version
      docker build -t docker-action:latest -f "$GITHUB_ACTION_PATH/Dockerfile" .
  
    shell: bash
  
  - name: "Run Image docker"
    run: |
      docker run -d docker-action:latest
    shell: bash